Fixed issue(?) where script would not run properly due to some print statements
For some reason these print functions do not like it when quotation marks are used when looking for JSON variable names and would instantly exit with the error:
SyntaxError: f-string: unmatched '['
The quotation marked have been replaced with apostrophes instead and the script functions as normal